# Generated by Django 4.2.15 on 2025-02-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='updated_at',
        ),
    ]
